/**
 * S10 / R26 — THE SEAM. Broker payload -> mapping -> rendered strip, end to end.
 *
 * WHAT THIS EXISTS TO COVER, and why `LaneStrip.shadowState.test.jsx` did not.
 * That suite states its own limitation honestly: it "compares RENDERED OUTPUT
 * FOR TWO STATE OBJECTS", and it BUILDS those objects by hand. The broker suite
 * (`lane_broker/tests/test_shadow_default_is_inert.py`) proves the other half —
 * that the `shadow` flag corresponds to real queueing behaviour, against a real
 * subprocess. Both halves were real. **The line between them was not tested.**
 *
 * That is L3's shape exactly: the record tests called the property directly,
 * the store tests passed hand-built dicts, and `to_row()` — the seam — wrote
 * nothing, under a green suite and a ✅ on the board.
 *
 * So this suite starts from a payload GENERATED BY THE REAL BROKER
 * (`fixtures/queue-payloads.generated.json`, written by
 * `lane_broker/tests/test_queue_payload_fixture.py`) and runs it through the
 * REAL mapping (`laneStripFrom`) into the REAL component. **There is no
 * hand-built lane object anywhere in this file.** If any link changes shape,
 * this reddens; that is the whole point.
 *
 * ── THE FINDING THE ARTEFACT MADE VISIBLE ──────────────────────────────────
 * The two generated payloads are IDENTICAL on every field except `shadow`:
 *
 *   live   -> {in_flight: null, queued: [], estimated_clear_seconds: 0.0, ...}
 *   shadow -> {in_flight: null, queued: [], estimated_clear_seconds: 0.0, ...}
 *
 * An idle live broker and a shadow broker agree on every number they publish.
 * **That is the measured proof that the flag cannot be inferred and must be
 * read** — and it is why a `=== true` that silently yields `false` renders the
 * live meter over a dead queue with nothing anywhere to contradict it.
 */
import { describe, it, expect } from "vitest";
import { render } from "@testing-library/react";
import LaneStrip from "../components/shell/LaneStrip";
import { laneStripFrom, LANE_STRIP_KEYS } from "../utils/laneMath";
import generated from "./fixtures/queue-payloads.generated.json";

const sessions = [{ id: "s1", name: "Session One", status: "idle" }];
const THRESHOLD = 30;

/** Payload -> mapping -> component. The chain under test, with nothing faked. */
function renderFromPayload(payload) {
  const lane = laneStripFrom(payload, null, THRESHOLD);
  return { lane, ...render(<LaneStrip sessions={sessions} lane={lane} />) };
}

describe("S10 wiring: the real /queue payload reaches the strip with its meaning intact", () => {
  it("the artefact is provider-generated and the two modes differ ONLY by `shadow`", () => {
    const { live, shadow } = generated;
    // If this ever fails, the premise of the whole row has changed: it would
    // mean a shadow broker is distinguishable from an idle one by its numbers,
    // and the flag would no longer be the only carrier of the distinction.
    const strip = (o) => Object.fromEntries(Object.entries(o).filter(([k]) => k !== "shadow"));
    expect(strip(shadow)).toEqual(strip(live));
    expect(shadow.shadow).toBe(true);
    expect(live.shadow).toBe(false);
  });

  it("SHADOW payload -> the strip says queueing is off (not that the lane is idle)", () => {
    const { lane, getByText } = renderFromPayload(generated.shadow);
    // The mapping carried the flag. This is the assertion that was missing.
    expect(lane.shadow).toBe(true);
    expect(getByText(/queueing off/i)).toBeTruthy();
  });

  it("LIVE payload -> the strip renders the meter, not the shadow note", () => {
    const { lane, queryByText } = renderFromPayload(generated.live);
    expect(lane.shadow).toBe(false);
    expect(queryByText(/queueing off/i)).toBeNull();
  });

  it("the two payloads render DIFFERENTLY — R10, pairwise, through the whole chain", () => {
    // Deliberately compares rendered HTML rather than the lane objects: the
    // lane objects differing proves the mapping ran, not that the difference
    // survives to the screen. A collapse anywhere downstream shows up here.
    const a = renderFromPayload(generated.shadow).container.innerHTML;
    const b = renderFromPayload(generated.live).container.innerHTML;
    expect(a).not.toEqual(b);
  });

  it("STRUCTURAL: the mapping's key set equals what LaneStrip reads, both ways", () => {
    const lane = laneStripFrom(generated.shadow, null, THRESHOLD);
    // Set equality, not a subset check — a subset would let every key be added
    // or dropped without a word, which is how three columns went unwritten in
    // L3. Both directions: a key the mapper stops producing is never rendered;
    // a key the component starts reading that the mapper never produces is
    // silently `undefined`, which `Number.isFinite` turns into a plausible 0.
    expect(new Set(Object.keys(lane))).toEqual(new Set(LANE_STRIP_KEYS));
  });

  it("a STRING \"true\" is not a shadow broker — the exact silent-false case", () => {
    // `=== true` is deliberate and this pins why. If the transport ever
    // stringifies the flag, the strip must NOT quietly claim a live queue... and
    // today it would. This asserts the CURRENT behaviour so the day someone
    // changes the comparison to a truthy check, they are told what they bought.
    const lane = laneStripFrom({ ...generated.shadow, shadow: "true" }, null, THRESHOLD);
    expect(lane.shadow).toBe(false);
  });
});
