/**
 * S9 / R26 — THE SEAM. Real handler payload -> buildLocalGroups -> rendered group.
 *
 * WHAT THIS COVERS THAT `modelCatalog.authStates.test.jsx` DOES NOT. That suite
 * proves `buildLocalGroups` renders four distinguishable groups, and
 * `tests/test_models_auth_states.py` proves the real handler emits four
 * distinguishable bodies. Both are real. **The exact JSON shape crossing
 * between them was joined by nothing** — the JS suite hand-builds its response
 * objects, so it agrees with itself by construction.
 *
 * S9 is not being downgraded: it tested three distinct links and measured the
 * live payload. This closes the structural exposure it shares with S10, using
 * the artefact generated by `tests/test_models_auth_fixture.py` from the real
 * ASGI handler.
 *
 * ── THE COLLAPSE THIS PINS, which is subtler than the one S9 closed ─────────
 * `modelCatalog.js:170` reads:
 *
 *     note: resp.reason === "forbidden" ? FORBIDDEN_NOTE : UNAUTHORIZED_NOTE
 *
 * **UNAUTHORIZED is the FALLBACK branch.** Every reason string that is not
 * exactly `"forbidden"` lands there. So if the provider ever renames that
 * value, a 403 silently renders as "Plexar did not accept the credential" —
 * telling a user whose key is VALID to go re-enter the one thing that is not
 * broken. That is the precise remedy-collapse S9's 401/403 split exists to
 * refuse, and nothing but the exact string prevents it. A hand-built fixture
 * cannot catch it, because the hand that writes the fixture writes the string.
 */
import { describe, it, expect } from "vitest";
import {
  buildLocalGroups,
  UNAUTHORIZED_NOTE,
  FORBIDDEN_NOTE,
} from "../modelCatalog.js";
import generated from "./fixtures/models-auth-states.generated.json";

const PROVIDER = { id: "plexar-vllm", label: "Plexar-vLLM", capabilities: ["models"] };

/** The real body, straight from the artefact, into the real consumer. */
function groupsFor(stateName) {
  return buildLocalGroups([PROVIDER], { "plexar-vllm": generated[stateName].body });
}

describe("S9 wiring: the handler's real bodies reach the picker with their meaning intact", () => {
  it("the artefact carries all four states the consumer branches on", () => {
    // Declared total, not a floor (R19) — a state silently dropping out of the
    // artefact would make every assertion below vacuously true about a smaller
    // world.
    const states = Object.keys(generated).filter((k) => k !== "_README");
    expect(new Set(states)).toEqual(
      new Set(["authorized", "unauthorized", "forbidden", "down"])
    );
  });

  it("REAL 401 body -> provider stays visible and gets the credential remedy", () => {
    const groups = groupsFor("unauthorized");
    expect(groups).toHaveLength(1);
    expect(groups[0].note).toBe(UNAUTHORIZED_NOTE);
  });

  it("REAL 403 body -> the OTHER remedy, decided by the provider's own string", () => {
    // This is the assertion the hand-built suite could not make honestly.
    expect(generated.forbidden.body.reason).toBe("forbidden");
    const groups = groupsFor("forbidden");
    expect(groups).toHaveLength(1);
    expect(groups[0].note).toBe(FORBIDDEN_NOTE);
    expect(groups[0].note).not.toBe(UNAUTHORIZED_NOTE);
  });

  it("REAL healthy body -> never labelled a credential problem", () => {
    // The consumer keys on the ABSENCE of `authorized`, so pin the absence in
    // the generated payload rather than trusting it.
    expect(generated.authorized.body).not.toHaveProperty("authorized");
    const groups = groupsFor("authorized");
    expect(groups[0].note).not.toBe(UNAUTHORIZED_NOTE);
    expect(groups[0].note).not.toBe(FORBIDDEN_NOTE);
    expect(groups[0].models.map((m) => m.localModelId)).toEqual(["qwen3-30b-instruct"]);
  });

  it("the four real bodies produce PAIRWISE DISTINCT groups — R10, end to end", () => {
    const states = ["authorized", "unauthorized", "forbidden", "down"];
    const rendered = states.map((s) => JSON.stringify(groupsFor(s)));
    for (let i = 0; i < rendered.length; i += 1) {
      for (let j = i + 1; j < rendered.length; j += 1) {
        expect(rendered[i], `${states[i]} vs ${states[j]} collapsed`).not.toEqual(rendered[j]);
      }
    }
  });

  it("STRUCTURAL: every literal the consumer branches on exists in the real payload", () => {
    // `modelCatalog.js` branches on `authorized === false` and
    // `reason === "forbidden"`. If the provider renames either, the consumer
    // does not error -- it takes the fallback path silently. Pin both against
    // what the handler actually emitted.
    expect(generated.unauthorized.body.authorized).toBe(false);
    expect(generated.forbidden.body.authorized).toBe(false);
    expect(generated.forbidden.body.reason).toBe("forbidden");
    expect(generated.unauthorized.body.reason).toBe("unauthorized");
  });
});
