# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for cockpit-server (Tauri sidecar)

import os
import re

block_cipher = None
root = os.path.dirname(os.path.abspath(SPEC))
frontend_dist = os.path.join(root, 'frontend', 'dist')

# Version resource: read the version out of frontend/package.json at spec time
# (never hard-code it here -- a stale version resource is worse than none, since
# it reads as authoritative in Task Manager / file Properties).
#
# CHANGED 2026-09-10: this used to read pyproject.toml, which is NOT one of the
# version sources a release bumps (package.json, tauri.conf, Cargo.toml and both
# lock files -- the set check-version-sources.mjs compares). It stopped moving at
# 2.1.21, so the 2.1.22-2.1.26 servers all told Windows they were 2.1.21 -- and
# during a live diagnosis the stale stamp read as "the wrong build is installed".
# package.json is the single source tauri.conf points at, so it cannot drift. This regenerates
# web/version_info.txt on every build; the checked-in file is a placeholder
# with zeroed version fields so the repo has something to diff against.
import json as _json
_package_json = os.path.join(root, 'frontend', 'package.json')
with open(_package_json, encoding='utf-8') as _f:
    _version = _json.load(_f).get('version', '')
if not re.fullmatch(r'\d+(\.\d+){1,3}', _version or ''):
    raise RuntimeError(f'no usable "version" in {_package_json}: {_version!r}')
_parts = [int(x) for x in _version.split('.')]
while len(_parts) < 4:
    _parts.append(0)
_filevers = tuple(_parts[:4])

_version_info_path = os.path.join(root, 'version_info.txt')
with open(_version_info_path, 'w', encoding='utf-8') as _f:
    _f.write(f'''# UTF-8
#
# Version resource for plexar-studio-server.exe.
# GENERATED by cockpit-server.spec from frontend/package.json's version
# -- do not hand-edit, this file is overwritten on every PyInstaller run.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={_filevers!r},
    prodvers={_filevers!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [StringStruct(u'CompanyName', u'Boord ITS'),
          StringStruct(u'FileDescription', u'Plexar Studio local server (keep running; Studio relaunches it)'),
          StringStruct(u'FileVersion', u'{_version}'),
          StringStruct(u'InternalName', u'plexar-studio-server.exe'),
          StringStruct(u'OriginalFilename', u'plexar-studio-server.exe'),
          StringStruct(u'ProductName', u'Plexar Studio'),
          StringStruct(u'ProductVersion', u'{_version}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
''')

# No winpty DLLs needed — we use a pure-ctypes ConPTY wrapper (conpty.py)
# that calls the Windows ConPTY API directly, bypassing pywinpty's C
# extension which causes 0xC0000142 in PyInstaller onefile bundles.

a = Analysis(
    [os.path.join(root, 'server.py')],
    pathex=[root],
    binaries=[],
    datas=[
        (frontend_dist, 'frontend_dist'),
        (os.path.join(root, 'codex_pricing.json'), '.'),
        # pricing_store seeds from this file; without it every sidecar start
        # logged a FileNotFoundError traceback for _MEI*/pricing_models.json.
        (os.path.join(root, 'pricing_models.json'), '.'),
        # GET /api/version reads the app version out of package.json -- the same
        # file tauri.conf.json points at and vite injects as VITE_APP_VERSION.
        # Without it bundled, _app_version() finds nothing in the sidecar and the
        # endpoint reports app: null in the DESKTOP build while being correct in
        # dev, which is the worst way for a version to be wrong.
        (os.path.join(os.path.dirname(frontend_dist), 'package.json'), '.'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'starlette',
        'starlette.middleware',
        'starlette.routing',
        'starlette.responses',
        'fastapi',
        'fastapi.responses',
        'winpty',
        'conpty',
        'dotenv',
        'websockets',
        'httpx',
        'multipart',
        'python_multipart',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='plexar-studio-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    icon=os.path.join(root, 'frontend', 'src-tauri', 'icons', 'icon.ico'),
    version=_version_info_path,
)
